version: '3.8'

services:
  database:
    build: ./database/
    image: mnaray/sql_injection_db:test
    container_name: usersdb
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  server:
    build: ./frontend/
    image: mnaray/sql_injection_server:test
    container_name: server
    restart: always
    depends_on:
      - database
    links:
      - database
    ports:
      - "3000:80"
