version: '3.8'

services:
  database:
    image: mnaray/sql_injection_db:test
    container_name: usersdb
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"

  # webserver:
  #   image: node:latest
  #   container_name: loginpage
  #   restart: always
  #   ports:
  #     - "3000:80"
